# Generated by Django 5.1.7 on 2025-04-22 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_answer_user_alter_question_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='dislike',
            new_name='count_dislikes',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='like',
            new_name='count_likes',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='comment',
            new_name='count_comments',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='dislike',
            new_name='count_dislikes',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='like',
            new_name='count_likes',
        ),
        migrations.AddField(
            model_name='profile',
            name='count_answers',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='count_comments',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='count_correct',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
