# Generated by Django 5.1.7 on 2025-04-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_dislike_answer_count_dislikes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='count',
            new_name='count_comments',
        ),
    ]
