# Generated by Django 5.1.7 on 2025-04-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_count_tag_count_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(default=None, max_length=150),
        ),
    ]
