# Generated by Django 5.1.7 on 2025-04-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_tag_rating_remove_tag_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dislikeanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dislikequestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='likeanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='likequestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='count_dislikes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='count_likes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='count_answers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='count_comments',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='count_correct',
        ),
        migrations.RemoveField(
            model_name='question',
            name='count_comments',
        ),
        migrations.RemoveField(
            model_name='question',
            name='count_dislikes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='count_likes',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='count_comments',
        ),
        migrations.AlterModelTable(
            name='answer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='dislikeanswer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='dislikequestion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='likeanswer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='likequestion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tag',
            table=None,
        ),
    ]
