# Generated by Django 5.1.7 on 2025-04-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_answer_options_alter_dislikeanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/avatars/default.png', upload_to='avatars/'),
        ),
    ]
