# Generated by Django 5.1.7 on 2025-04-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='C:\\Users\\vlokh\\Desktop\\ask_lokhanev\\media\\avatars/default.png', upload_to='avatars/'),
        ),
    ]
